python_library(
    name = 'plugin',
    dependencies=[
        'plugins/python/python_protoc/tasks',
        'plugins/python/python_protoc/targets',
        'src/python/pants/build_graph',
        'src/python/pants/goal:task_registrar',
    ],
    register_goals=True,
)