python_library(
    name="scheduler",
    dependencies=[
        "3rdparty/python:google-cloud-storage",
        "3rdparty/python:google-cloud-pubsub",
        "3rdparty/python:google-cloud-core",
        "3rdparty/python:google-auth",
        "3rdparty/python:Jinja2",
        "generated/python:grpc_generated_services",
    ],
    sources = globs("*.py")
)