python_library(
    name="video-transcoder",
    dependencies=[
        "3rdparty/python:google-cloud-storage",
        "3rdparty/python:google-cloud-core",
        "3rdparty/python:google-auth",
        "3rdparty/python:google-api-core",
    ],
    sources = globs("*.py")
)