apiVersion: k8s.uob.tv/v1
kind: HlsStream
metadata:
  name: stream-abcd
  namespace: video-proc-streaming
spec:
  streamKey: abcd
  rtmpService: ossrs-ingestion-service
  ip: 10.14.123.41
  port: 1935
  channelId: 1234
