python_binary(
    name = "user-authen-server",
    dependencies = [
        "src/python/user_authen/app:user-authen-app"
    ],
    source="main.py",
    platforms=[
        'current',
        'linux-x86_64',
        'macosx-10.12-x86_64',
    ],
)