apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: hls-cluster-service-backends
spec:
  host: hls-cluster-service
  subsets:
  - name: {{ streamKey }}
    labels:
      stream-key: {{ streamKey }}
