apiVersion: apps/v1
kind: Deployment
metadata:
  name: hls-stream-server-abcd-1234-deployment
  namespace: video-proc-streaming
  labels:
    app: hls-stream-server
    stream-key: abcd-1234
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hls-stream-server
      stream-key: abcd-1234
  template:
    metadata:
      labels:
        app: hls-stream-server
        stream-key: abcd-1234
    spec:
      containers:
        - name: ffmpeg
          image: eu.gcr.io/uob-tv-project-dev/uob-tv-ffmpeg:1-3
          imagePullPolicy: IfNotPresent
          command: ["/start-ffmpeg.sh"]
          env:
            - name: RTMP_SOURCE
              value: rtmp://10.31.243.186:1935/live/stream
            - name: HLS_OUTPUT_DIR
              value: /var/ffmpeg-out
            - name: STREAM_KEY
              value: abcd-1234
            - name: HLS_FILE_NAME
              value: stream
            - name: STREAM_ID
              value: "1234"
          ports:
          - containerPort: 1935
          resources:
            requests:
              memory: "128Mi"
              cpu: "80m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          volumeMounts:
            - name: video-data
              mountPath: /var/ffmpeg-out
        - name: nginx
          image: eu.gcr.io/uob-tv-project-dev/nginx:1-5
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          resources:
            requests:
              memory: "60Mi"
              cpu: "30m"
            limits:
              memory: "120Mi"
              cpu: "150m"
          volumeMounts:
            - name: video-data
              mountPath: /var/ffmpeg-out
      volumes:
        - name: video-data
          emptyDir: {}
