kind: Service
apiVersion: v1
metadata:
  name: hls-cluster-service
  namespace: video-proc-streaming
spec:
  selector:
    app:  hls-streamer
  type:  ClusterIP
  ports:
  - name: http-hls
    port: 8080
    targetPort: 8080
