apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: uob-tv-internal-web-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http-internal-web
      protocol: HTTP
    hosts:
    - jaeger.uob-tv.co.uk
    - grafana.uob-tv.co.uk
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https-internal-web
      protocol: HTTPS
    hosts:
    - jaeger.uob-tv.co.uk
    - grafana.uob-tv.co.uk
    tls:
      mode: SIMPLE
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
