apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: uob-tv-internal-web-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "jaeger.uob-tv.co.uk"
    - "grafana.uob-tv.co.uk"