apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
    name: uob-tv-ingestion-gateway
    namespace: video-proc-streaming
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 1935
        name: rtmp-ingest
        protocol: TCP
      hosts:
        - "ingest.uob-tv.co.uk"