#https://kubernetes.io/docs/concepts/storage/storage-classes/#gce-pd
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: slow
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: none