apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
    name: uob-tv-ingestion-gateway
    namespace: video-proc-streaming
spec:
    selector:
        istio: ingressgateway # use istio default controller
    servers:
    - port:
        number: 1935
        name: rtcmp
        protocol: TCP
      hosts:
        - "ingestion.uob-tv.co.uk"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
    name: uob-tv-ingestion-routes
    namespace: video-proc-streaming
spec:
    hosts:
    - "*"
    gateways:
    - uob-tv-ingestion-gateway
    tcp:
    - match:
        - port: 1935
      route:
      - destination:
            host: ossrs-rtmp-ingestion-service
