kind: Service
apiVersion: v1
metadata:
  name: ossrs-rtmp-ingestion-service
  namespace: video-proc-streaming
spec:
  selector:
    app:  ossrs
  type:  ClusterIP
  ports:
  - name:  rtmp
    port:  1935
    targetPort:  1935
---
kind: Service
apiVersion: v1
metadata:
  name: ossrs-http-api
  namespace: video-proc-streaming
spec:
  selector:
    app:  ossrs
  type:  ClusterIP
  ports:
  - name:  http-api
    port:  1985
    targetPort:  1985