apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-authen-deployment
  namespace: app-backends
  labels:
    app: user-authen-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-authen-server
  template:
    metadata:
      labels:
        app: user-authen-server
        version: "v1"
    spec:
      containers:
      - name: user-authen-server
        image: eu.gcr.io/uob-tv-project-dev/user-authen-server:1
        env: 
          - name: API_AUTH_JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: userAuthSecret
                key: apiAuthJwtSecret
          - name: GOOGLE_SIGN_IN_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: userAuthSecret
                key: googleSignInClientId
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: "80Mi"
            cpu: "200m"
          limits:
            memory: "160Mi"
            cpu: "400m"
