apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  namespace: app-backends
  labels:
    app: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
        version: "v1"
    spec:
      containers:
      - name: users-server
        image: eu.gcr.io/uob-tv-project-dev/users-server:1
        ports:
          - containerPort: 6000
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "400m"
