apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  namespace: app-backends
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
        version: "v1"
    spec:
      containers:
      - name: hello-world-server
        image: eu.gcr.io/uob-tv-project-dev/hello-world-server:1
        ports:
          - containerPort: 6000
        resources:
          requests:
            memory: "64Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "50m"
