apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-world
  namespace: app-backends
spec:
  hosts:
  - "*"
  gateways:
  - uob-tv-api-gateway
  tcp:
    
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: hello-world-destination
spec:
  host: hello-world.prod.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
