kind: Role
apiVersion: rbac.authorization.k8s.io/v1 
metadata:
  name: hls-streams-admin-edit
  namespace: video-proc-streaming
rules:
- apiGroups: ["k8s.uob.tv"]
  resources: ["hlsstreams", 'hlsstream', "hlsstreams.k8s.uob.tv", "HlsStream"]
  verbs: ["*"]
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods", "services"]
  verbs: ["*"]
- apiGroups: ["networking.istio.io"]
  resources: ["virtualservices", "virtualservice"]
  verbs: ["*"]
