apiVersion: apps/v1
kind: Deployment
metadata:
  name: hls-cluster-controller-deployment
  namespace: video-proc-streaming
  labels:
    app: hls-cluster-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hls-cluster-controller
  template:
    metadata:
      namespace: video-proc-streaming
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: hls-cluster-controller
    spec:
      containers:
        - name: hls-cluster-controller
          image: eu.gcr.io/uob-tv-project-dev/hls_cluster_controller:1-7
          imagePullPolicy: Always
          ports:
          - containerPort: 8001
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
