apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: googleapi
  namespace: app-backends
spec:
  hosts:
  - "*.googleapis.com"
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS